# Numpy

Learning Objectives:
* Students will gain understanding of the motivation for numpy ndarray objects as a computationally efficient alternative to Python lists.
* Students will practice basic indexing, slicing, concatenating, and splitting operations on numpy ndarrays.
* Students will practice basic application of universal functions, aggregation functions, and broadcasting on ndarray broadcasting.

Readings before class:

* Jake VanderPlas.  [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/):
  * [Chapter 2 - Introduction to Numpy through section "Computation on Arrays: Broadcasting"](https://jakevdp.github.io/PythonDataScienceHandbook/) _If you have time to read further, you'll benefit from seeing some of the masking and sorting computation examples that follow.  In this course, we will primarily use pandas DataFrame objects for computations on data._

Before class:
* Perform the **To-Do** tasks below as you do the reading.  You are encouraged to add code blocks and play with the forms to gain understanding and comfort with them.

In class:
* We will work together on the exercises in section "In Class".

Homework after class:
* Complete the section labeled "Homework" below before the next class when it will be collected.

In [8]:
# Place your imports here.

import numpy as np
import pandas as pd
np.random.seed(0)  # seed for reproducibility


## Motivations

One thing you may have noticed is that there are a number of ways to represent a sequence of numbers:

In [9]:
print('Python list')
# Python list
l = [1, 2, 3]
print(l, type(l))

print('--> numpy ndarray')
# Python list to numpy ndarray
a = np.asarray(l)
print(a, type(a))

print('--> pandas Series')
# numpy ndarray to pandas Series
s = pd.Series(a)
print(s, type(s))

print('--> pandas DataFrame')
# pandas Series to pandas DataFrame
df = pd.DataFrame(s)
print(df, type(df))

print('--> pandas Series')
# pandas DataFrame to pandas Series
s = df[0]
print(s, type(s))

print('--> numpy ndarray')
# pandas Series to numpy ndarray
a = np.asarray(s)
print(a, type(a))

print('--> Python list')
# numpy ndarray to Python list
l = a.tolist()
print(l, type(l))

Python list
[1, 2, 3] <class 'list'>
--> numpy ndarray
[1 2 3] <class 'numpy.ndarray'>
--> pandas Series
0    1
1    2
2    3
dtype: int32 <class 'pandas.core.series.Series'>
--> pandas DataFrame
   0
0  1
1  2
2  3 <class 'pandas.core.frame.DataFrame'>
--> pandas Series
0    1
1    2
2    3
Name: 0, dtype: int32 <class 'pandas.core.series.Series'>
--> numpy ndarray
[1 2 3] <class 'numpy.ndarray'>
--> Python list
[1, 2, 3] <class 'list'>


In this chapter and the next of VanderPlas' text, we will come to a better understanding of why there is a distinctive benefit to having these forms.  The short answer is that Python list versatility trades off computational efficiency.  The numpy library gives us higher performance multidimensional arrays with efficient operations over homogenous data.  Pandas builds on top of numpy ndarrays to provide support for tabular data and versatile table operations.  Here we summarize the motivation for numpy.

Python is a dynamically typed language, meaning that the type of a variable is determined dynamically according to what value is currently assigned to it.  This means that each value is a reference to an object that contains not only the data, but the data type, size, number of variables that reference it (the "reference count", so that the memory can be reclaimed or "garbage collected" when the count goes to zero), all in addition to the data itself!  This makes iterative operations through lists much slower than in other languages like C, C++ and Java.

Numpy allows a programmer to create an array of a single type of data so that there is informational overhead only for the list itself, and data is stored as a list of just the data itself.  A picture of this different is provided by VanderPlas:

![ndarray versus Python list](https://jakevdp.github.io/PythonDataScienceHandbook/figures/array_vs_list.png)

Much of the reading is how to perform various tasks.  The best way to learn is through practiced application.  Before class, in class, and after class in homework, you will exercise the core skills of the reading.  First, however, are questions best answered by well-formed web search queries.

**To-Do: Look up and perform the following additional conversions.**

In [10]:
import numpy as np
import pandas as pd
l = [1, 2, 3]

# Convert Python list l as directly as possible to a pandas Series s.
s = pd.Series(l)
print(s, type(s))


# Convert pandas Series s as directly as possible to a Python list.
l = s.tolist()
print(l, type(l))


0    1
1    2
2    3
dtype: int64 <class 'pandas.core.series.Series'>
[1, 2, 3] <class 'list'>


### Creating Arrays from Scratch

**To-Do: Initialize the following numpy arrays in the simplest way possible and print the result to verify correctness.**

In [11]:
# Create and print numpy ndarray of 20 integer zeros.



# Create and print an array filled with -24, -21, -18, ..., 18, 21, 24.



# Create and print a 4-by-4 array of normally distributed random values with mean 10 and standard deviation 5.



# Create and print an uninitialized array of 20 integers.



### Numpy Array Attributes

**To-Do:**

In [12]:
# Create and print a 2-by-3-by-4 array filled with 1.23.



# Use members of that array to print the number of dimensions, shape (size of each dimension), size (total count of values), and type.



### No-copy and copy views

**To-Do:**

In [13]:
a = np.arange(1, 17).reshape((4, 4))
print(a)

# Create a copy 'c' of a view of the middle two columns of array 'c'.



# Assign the first row, first column of 'c' to value 42.  Print 'c' and 'a' to show that the change to copy 'c' didn't affect original 'a'.



# Create a non-copy 'nc' of a view of the middle two rows of array 'a'.



# Use negative indexing to assign the last row and column of 'nc' to 0.  Print 'nc' and 'a' to show that the change to no-copy slice 'nc' affected original 'a'.



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### Array Splitting

**To-Do:**

In [14]:
a = np.arange(0, 10)
print(a)
a2 = np.arange(1, 17).reshape((4, 4))
print(a2)

# Assign arrays 'b', 'c', and 'd' to be a split of 'a' at indices 3 and 7.  Print 'b', 'c', and 'd'.



# Print the result of splitting a2 into its first column and last three columns.



# Print the result of splitting a2 into its first three rows and its last row.




[0 1 2 3 4 5 6 7 8 9]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### Aggregation

**To-Do:**

In [15]:
a = np.array([32, 8, 2])

# Use numpy aggregation to print the sum of the values of 'a'.


# Use numpy aggregation to print the accumulated values that were partial sums on the way to the previous result ([32 40 42]).


# Use numpy aggregation to print the product of the values of 'a'.



# In Class

First, check your pre-class work above with each other.

Then, work together to complete the following exercises.

Look up and perform the following additional conversions.

In [16]:
a = np.array([1, 2, 3])

# Convert numpy ndarray a as directly as possible to a pandas Dataframe df.  Print the result and the type.



# Convert pandas Dataframe df as directly as possible to a numpy ndarray a.  Print the result and the type.



### Creating Arrays from Scratch

In [17]:
# Create and print numpy ndarray of 15 floating-point ones.



# Create and print an array of 10 values evenly spaced between -5 and 5



# Create and print a 3-by-11 array of random integers in from -1 to 1 inclusive.



### Array Indexing: Accessing Single Elements

In [18]:
# Create and print a 4-by-4 numpy array with values 1 through 16 left-to-right, top-to-bottom.



# Change the entry in the second row and third column to be 20.  Print the array.



# Use negative indexing to set the entry in the second to last row and second to last column to be 0.  Print the array.



### Array slicing: One-dimensional subarrays

In [19]:
# Create and print an array with integer values 0 through 9 using function arange.



# Use array slicing to slice subrange indices 5 through 7 inclusive and print the slice.



# Use array slicing to slice all even index values and print the slice.



# Use a negative step with slicing to print the array reversed.  Omit any slicing values that you can.



### Reshaping Arrays

In [20]:
a = np.arange(1, 17).reshape((4, 4))
print(a)

# Reshape array 'a' to have 2 rows and 8 columns.  Print the result.



# Create a copy 'c' of the first row of reshaped 'a' and reshape it to be a single column.  Print the result.



# Do the same with copy 'c2', but using newaxis instead of reshape.




[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### UFuncs: Universal Functions

For each of the following, apply universal functions to perform operations efficiently.

In [21]:
a = np.arange(1, 4)
print(a)

# Print the array of array 'a' value reciprocals.



# Print the array formed by adding array 'a' to itself.



# Print the array of 5 to the power of each value of 'a'.




[1 2 3]


### Numpy Aggregation Functions

For each of the following, apply Numpy's fast built-in aggregation functions.

In [22]:
np.random.seed(0)
a = np.arange(0,16)
np.random.shuffle(a)
a = a.reshape((4, 4))
print(a)

# Use aggregation to print the maximum value of 'a', the maximum values of each row, and the maximum values of each column.



# Use aggregation to print the row-based index of the minimum value of 'a'.  The row-based index is the index if we reshaped the array into a single row.



# Use aggregation to print the mean of the values of 'a'.



[[ 1  6  8  9]
 [13  4  2 14]
 [10  7 15 11]
 [ 3  0  5 12]]


# Homework

(0) Complete the in-class exercises.  (This may be done with others beyond your assigned pairs.)

(1) Look up and perform the following additional conversions.

In [25]:
l = [1, 2, 3]

# Convert Python list l as directly as possible to a pandas Dataframe df.  Print the result and the type.
df = pd.DataFrame(l)
print(df, type(df))


# Convert pandas Dataframe df as directly as possible to a Python list.  Print the result and the type.
s = df[0]

list = s.tolist()
print(list)


   0
0  1
1  2
2  3 <class 'pandas.core.frame.DataFrame'>
[1, 2, 3]


(2) Creating Arrays from Scratch

In [27]:
# Create and print a 4 row, 2 column numpy array filled with the integer value 42.

print(np.full((2, 4), 42))

# Create a 5-by-5 array of uniform random numbers in the range [0, 1).

print(np.random.random((5, 5)))

# Create and print a 5-by-5 identity matrix.
print(np.eye(5))


[[42 42 42 42]
 [42 42 42 42]]
[[0.32414101 0.14967487 0.22232139 0.38648898 0.90259848]
 [0.44994999 0.61306346 0.90234858 0.09928035 0.96980907]
 [0.65314004 0.17090959 0.35815217 0.75068614 0.60783067]
 [0.32504723 0.03842543 0.63427406 0.95894927 0.65279032]
 [0.63505887 0.99529957 0.58185033 0.41436859 0.4746975 ]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


(3) Array slicing: Multidimensional Arrays

In [37]:
a = np.arange(1, 17).reshape((4, 4))
print(a)

# Use array slicing to print the slice of array 'a' with values:
#[[ 6  7]
# [10 11]]
print(a[1:3, 1:3])


# Use array slicing to print the slice of array 'a' with values:
#[[ 5  7]
# [13 15]]

print(a[1::2, ::2])

# Combine indexing and slicing to print the second row of array 'a':

print(a[1])

# Combine indexing and slicing to print the third column of array 'a':

print(a[::,2:3])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 6  7]
 [10 11]]
[[ 5  7]
 [13 15]]
[5 6 7 8]
[[ 3]
 [ 7]
 [11]
 [15]]


(4) Array concatenation

In [41]:
a = np.arange(1, 17).reshape((4, 4))
print(a)

# Print the horizontal (row) concatenation of 'a' with 'a'.

print(np.concatenate([a, a], axis=0))

# Print the vertical (column) concatenation of 'a' with 'a'.

print(np.concatenate([a, a], axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4  1  2  3  4]
 [ 5  6  7  8  5  6  7  8]
 [ 9 10 11 12  9 10 11 12]
 [13 14 15 16 13 14 15 16]]


(5) UFuncs: Universal Functions

For each of the following, apply universal functions to perform operations efficiently.

In [42]:
a = np.arange(-0.5, 0.5, .25)
print(a)

# Print the array with absolute values of 'a' values.
print(np.abs(a))

# Print the array with the cosines of 'a' values.
print(np.cos(a))

# Print the array with the inverse tangents of 'a' values.
print(np.arctan(a))

# Print the array with 10 raised to the powers of 'a' values.
print(np.power(10, a))


[-0.5  -0.25  0.    0.25]
[0.5  0.25 0.   0.25]
[0.87758256 0.96891242 1.         0.96891242]
[-0.46364761 -0.24497866  0.          0.24497866]
[0.31622777 0.56234133 1.         1.77827941]


(6) Broadcasting

Use broadcasting to perform the following operation:

In [52]:
a = np.arange(1, 10)
print(a)
b = np.arange(10)[:, np.newaxis]

# Use broadcasting with 'a' and a column vector of 'a' to print the entries of a multiplication table with 9 rows and 9 columns showing products 1*1 (upper-left) through 9*9 (lower-right).
print(a*b[1:])


[1 2 3 4 5 6 7 8 9]
[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]


(end of homework)